# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-05 01:34
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Naem of container')),
                ('config', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'verbose_name': 'Container',
                'db_table': 'container',
            },
        ),
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('container', models.ManyToManyField(blank=True, db_table='expedition_has_container', null=True, related_name='expedition', to='nepal.Container')),
            ],
            options={
                'verbose_name': 'Expedition',
                'db_table': 'expedition',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('so', models.CharField(max_length=40)),
                ('provider', models.CharField(max_length=20)),
                ('ip', models.GenericIPAddressField()),
                ('docker_port', models.IntegerField(default=2375)),
                ('fqdn', models.CharField(blank=True, max_length=50, null=True)),
                ('ready', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Node',
                'db_table': 'node',
            },
        ),
        migrations.AddField(
            model_name='container',
            name='nodes',
            field=models.ManyToManyField(db_table='container_has_node', related_name='containers', to='nepal.Node', verbose_name='Container'),
        ),
    ]
