# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nepal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='nodes',
            field=models.ManyToManyField(blank=True, db_table='container_has_node', related_name='containers', to='nepal.Node', verbose_name='Container'),
        ),
        migrations.AlterField(
            model_name='container',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Naem of container'),
        ),
    ]
