# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='docker_port',
            field=models.IntegerField(default=2375),
        ),
        migrations.AlterField(
            model_name='node',
            name='provider',
            field=models.CharField(max_length=20),
        ),
    ]
