# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_auto_20160725_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='password',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='private_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
